# Generated by Django 2.2.4 on 2020-03-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='add_todo',
            field=models.CharField(max_length=20),
        ),
    ]
