# Generated by Django 2.2.4 on 2020-03-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200310_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='add_todo',
            field=models.CharField(max_length=100),
        ),
    ]
